flask_chirper/main/routes.py
from secrets import randbits
from datetime import datetime
from flask import render_template, redirect, url_for
from flask.blueprints import Blueprint
from flask_login import current_user, login_required
from flask_chirper import db
from flask_chirper.models import User, Post, follower, Message
from flask_chirper.main.forms import MessageForm
from flask_chirper.post.forms import PostForm


main = Blueprint('main', __name__)

@main.route('/home', methods = ['GET', 'POST'])
@login_required
def home():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(id = randbits(60), content = form.content.data, author = current_user)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('main.home'))

    return render_template('home.html', form = form)


@main.route('/explore', methods = ['GET', 'POST'])
def explore():
    return render_template('explore.html', trends = trends, happenings = happenings)


@main.route('/notifications')
@login_required
def notifications():
    return render_template('notifications.html')


@main.route('/notifications/mentions')
@login_required
def notifications_mentions():
    return render_template('notifications_mentions.html')


@main.route('/messages')
@login_required
def messages():
    current_user.last_read_message_at = datetime.utcnow()
    db.session.commit()
    
    return render_template('messages.html')


@main.route('/messages/compose')
@login_required
def messages_compose():
    return render_template('messages_compose.html')


@main.route('/messages/<int:counterpart_id>-<int:currentuser_id>', methods = ['GET', 'POST'])
@login_required
def messages_counterpart(counterpart_id, currentuser_id):
    if currentuser_id != current_user.id or User.query.get(counterpart_id) is None: 
        return redirect(url_for('main.messages'))

    counterpart = User.query.get(counterpart_id)

    form = MessageForm()
    if form.validate_on_submit():
        message = Message(id = randbits(60), sender_id = current_user.id, \
            recipient_id = counterpart.id, body = form.message.data)
        db.session.add(message)
        db.session.commit()
        return redirect(url_for('main.messages_counterpart', \
            counterpart_id = counterpart_id, currentuser_id = current_user.id))
    
    message_history = current_user.messages_received.filter_by(
        sender_id = counterpart.id).union(current_user.messages_sent.filter_by(
            recipient_id = counterpart_id)).order_by(Message.created_at)

    return render_template('messages_counterpart.html', form = form, \
        counterpart_id = counterpart_id, currentuser_id = currentuser_id, counterpart = counterpart, \
            message_history = message_history)


@main.route('/messages/<int:counterpart_id>-<int:currentuser_id>/info')
@login_required
def messages_counterpart_info(counterpart_id, currentuser_id):
    if currentuser_id != current_user.id or User.query.get(counterpart_id) is None: 
        return redirect(url_for('main.messages'))

    counterpart = User.query.get(counterpart_id)

    return render_template('messages_counterpart_info.html', \
        counterpart_id = counterpart_id, currentuser_id = currentuser_id, \
        counterpart = counterpart)


@main.route('/follower_requests')
@login_required
def followerRequests():
    return render_template('followerRequests.html')


# i
@main.route('/bookmarks')
@login_required
def bookmarks():
    return render_template('bookmarks.html')


# i
@main.route('/lists/create')
@login_required
def lists_create():
    return render_template('lists_create.html')


# i
@main.route('/lists/add_member')
@login_required
def lists_addMember():
    return render_template('lists_addMember.html')


# i
@main.route('/trends')
@login_required
def trends():
    return render_template('trends.html', trends = trends)


# i
@main.route('/timeline')
@login_required
def timeline():
    return render_template('timeline.html', happenings = happenings)


# i
@main.route('/connectPeople')
@login_required
def connectPeople():
    return render_template('connectPeople.html')


# i
@main.route('/display')
def display():
    return render_template('display.html')


# i
@main.route('/keyboard_shortcuts')
def keyboardShortcuts():
    return render_template('keyboardShortcuts.html')




trends = [
    {
        'label': 'label 1',
        'topic': 'topic 1',
        'content': 'content 1',
        'chirp_count': 'count 1'
    },
    {
        'label': 'label 2',
        'topic': 'topic 2',
        'content': 'content 2',
        'chirp_count': 'count 2'
    }
]

happenings = [
    {
        'label': 'label 1',
        'time': 'time 1',
        'title': 'title 1'
    },
    {
        'label': 'label 2',
        'time': 'time 2',
        'title': 'title 2'
    }
]

people = [
    {   
        'icon': 'icon 1',
        'username': 'username 1',
        'handle': '@handle 1'
    },
    {
        'icon': 'icon 2',
        'username': 'username 2',
        'handle': '@handle 2'
    }
]

flask_chirper/post/routes.py
from secrets import randbits
from flask import Blueprint, render_template, redirect, url_for, flash, request, abort
from flask_login import login_required, current_user
from flask_chirper import db
from flask_chirper.models import Post
from flask_chirper.post.forms import PostForm


post = Blueprint('post', __name__)

@post.route('/<handle>/status/<int:post_id>', methods = ['GET', 'POST'])
def status(handle, post_id):
    post = Post.query.get_or_404(post_id)

    if handle != post.author.handle:
        handle = post.author.handle
        post_id = post.id
        return redirect(url_for('post.status', handle = handle, post_id = post_id))
    
    return render_template('status.html', post = post)


@post.route('/<handle>/status/<int:post_id>/likes')
@login_required
def status_likes(handle, post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('status_likes.html', post = post)



@post.route('/<handle>/status/<int:post_id>/analytics', methods = ['GET'])
@login_required
def status_analytics(handle, post_id):
    post = Post.query.get_or_404(post_id)

    if post.author != current_user:
        return redirect(url_for('post.status', handle = handle, post_id = post_id))

    if handle != post.author.handle:
        handle = post.author.handle
        post_id = post.id
        return redirect(url_for('post.status_analytics', handle = handle, post_id = post_id))

    return render_template('status_analytics.html', post = post)


@post.route('/<handle>/status/<int:post_id>/update', methods = ['GET', 'POST'])
@login_required
def update_chirp(handle, post_id):
    post = Post.query.get_or_404(post_id)

    if handle != post.author.handle:
        handle = post.author.handle
        post_id = post.id
        return redirect(url_for('post.status', handle = handle, post_id = post_id))

    # route forbidded if it's not post owner
    if post.author != current_user:
        abort(403)

    # pre-fill content
    form = PostForm()
    if request.method == 'GET':
        form.content.data = post.content
    
    if form.validate_on_submit():
        post.content = form.content.data
        # post.created_at = datetime.utcnow()  optional
        db.session.commit()
        # flash('Your chirp has been updated. ', 'success')
        return redirect(url_for('post.status', handle = handle, post_id = post.id))

    return render_template('status_update.html', post = post, form = form)


@post.route('/<handle>/status/<int:post_id>/delete', methods = ['POST'])
@login_required
def delete_chirp(handle, post_id):
    post = Post.query.get_or_404(post_id)
    users = post.liked_by.all()

    if post.author != current_user:
        abort(403)
    
    for user in users:
        post.liked_by.remove(user)
    db.session.commit()
    
    db.session.delete(post)
    db.session.commit()
    flash('Your chirp was deleted', 'success')
    return redirect(url_for('user.profile', handle = current_user.handle))


@post.route('/<handle>/status/<int:post_id>/like', methods = ['POST'])
@login_required
def like_chirp(handle, post_id):
    post = Post.query.get(post_id)
    
    current_user.like(post)
    db.session.commit()

    return redirect(url_for('main.home'))


@post.route('/<handle>/status/<int:post_id>/unlike', methods = ['POST'])
@login_required
def unlike_chirp(handle, post_id):
    post = Post.query.get(post_id)

    current_user.unlike(post)
    db.session.commit()

    return redirect(url_for('main.home'))


@post.route('/compose/chirp', methods = ['GET', 'POST'])
@login_required
def compose_chirp():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(id = randbits(60), content = form.content.data, author = current_user)  # from the backref in db
        db.session.add(post)
        db.session.commit()
        flash('Your Chirp was sent. View')
        return redirect(url_for('user.profile', handle = current_user.handle))
    return render_template('compose_chirp.html', form = form)

flask_chirper/user/routes.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, current_user
from flask_chirper import db
from flask_chirper.models import User, Post, follower


user = Blueprint('user', __name__)

@user.route('/<handle>')
def profile(handle):
    user = User.query.filter_by(handle = handle).first_or_404()

    posts = Post.query.filter_by(user_id = user.id).order_by(Post.created_at.desc()).all()
    posts_count = len(posts)

    if current_user.is_authenticated:
        following_status = current_user.is_following(user)
    else: 
        following_status = None

    return render_template('profile.html', user = user, posts = posts, posts_count = posts_count, \
        following_status = following_status)


@user.route('/<handle>/with_replies')
def profile_with_replies(handle):
    user = User.query.filter_by(handle = handle).first_or_404()
    return render_template('profile_with_replies.html', user = user)


@user.route('/<handle>/media')
def profile_media(handle):
    user = User.query.filter_by(handle = handle).first_or_404()

    if not current_user.is_authenticated:
        return redirect(url_for('user.profile', handle = user.handle))
        
    return render_template('profile_media.html', user = user)


@user.route('/<handle>/likes')
def profile_likes(handle):
    user = User.query.filter_by(handle = handle).first_or_404()

    if not current_user.is_authenticated:
        return redirect(url_for('user.profile', handle = user.handle))

    if current_user.is_authenticated:
        posts = user.posts_liked.order_by(Post.created_at.desc()).all()
        posts_count = len(posts)

    return render_template('profile_likes.html', user = user, posts = posts, posts_count = posts_count)


# needs fixing <handle>
@user.route('/profile/lists')
@login_required
def profile_lists():
    return render_template('profile_lists.html')


@user.route('/<handle>/moments')
def profile_moments(handle):
    return render_template('profile_moments.html')


@user.route('/<handle>/topics')
def profile_topics(handle):
    return render_template('profile_topics.html')


@user.route('/<handle>/followers_you_know')
@login_required
def profile_followersYouKnow(handle):
    user = User.query.filter_by(handle = handle).first()
    if user == current_user:
        return redirect(url_for('user.profile', handle = user.handle))

    return render_template('profile_followersYouKnow.html', user = user)


@user.route('/<handle>/followers')
@login_required
def profile_followers(handle):
    user = User.query.filter_by(handle = handle).first()
    return render_template('profile_followers.html', user = user)


@user.route('/<handle>/following')
@login_required
def profile_following(handle):
    user = User.query.filter_by(handle = handle).first()
    return render_template('profile_following.html', user = user)


@user.route('/<handle>/suggested')
@login_required
def profile_suggested(handle):
    user = User.query.filter_by(handle = handle).first()
    return render_template('profile_suggested.html', user = user)


@user.route('/<handle>/follow', methods = ['POST'])
@login_required
def follow(handle):
    user = User.query.filter_by(handle = handle).first_or_404()
    
    current_user.follow(user)
    db.session.commit()
    return redirect(url_for('user.profile', handle = user.handle))


@user.route('/<handle>/unfollow', methods = ['POST'])
@login_required
def unfollow(handle):
    user = User.query.filter_by(handle = handle).first_or_404()

    current_user.unfollow(user)
    db.session.commit()
    return redirect(url_for('user.profile', handle = user.handle))

flask_chirper/templates/connectPeople.html
connect_people page

flask_chirper/templates/explore.html
{% extends 'layout.html' %}

{% block title %}Explore{% endblock title%}
{% block header %}
<div class="">
    <div class="flex flex-row items-center justify-start w-124 py-1 px-3 space-x-1
    text-gray-600 bg-gray-800 bg-opacity-75 rounded-full overflow-hidden
       border border-transparent focus-within:border-blue-500 focus-within:text-blue-500
       focus-within:bg-gray-900">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
            class="w-5 h-5 stroke-current focus:text-blue-500 inline">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
        </svg>
        <form method="POST" action="" class="inline pl-1">
            <label for="search"></label>
            <input name="search" type="text" placeholder="Search Chirper"
                class="text-base text-white bg-gray-800 bg-opacity-0 outline-none">
        </form>
    </div>
</div>
{% endblock header %}
{% block svg %}
<div class="svg-bg-div">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
        class="w-6 h-6 stroke-current text-blue-500">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
            d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
    </svg>
</div>
{% endblock svg %}



{% block content %}
<div>
    <!-- event -->
    <a href="#">
        <div style="background-image:url({{ url_for('static', filename = 'img/ocean6.jpg') }})"
            class="bg-local bg-cover bg-center">
            <div class="w-full h-80 flex flex-col justify-end px-4 py-3
        bg-gradient-to-b from-transparent to-gray-900">
                <div class="flex flex-row items-center space-x-1">
                    <div class="text-sm">Topic</div>
                    <div>⋅</div>
                    <div class="text-sm">Trending</div>
                </div>
                <div class="text-xl font-bold">The power of ocean</div>
            </div>
        </div>
    </a>

    <!-- trends for you -->
    <div class="border-t-8 border-gray-800">
        <div>
            <h2 class="border-b border-gray-700 text-xl font-bold p-3 pl-4">Trends for you</h2>
            {% for trend in trends %}
            <div class="border-b border-gray-700 pl-4 pr-3 pt-1 pb-3 
            hover:bg-gray-800 hover:bg-opacity-25">
                <div class="flex flex-row items-center justify-between">
                    <div class="flex flex-row text-sm text-gray-600 space-x-1">
                        <div>{{ trend.label }}</div>
                        <div>⋅</div>
                        <div>Trending</div>
                    </div>
                    <!-- svg -->
                    <button class="focus:outline-none hover:text-blue-500">
                        <div class="rounded-full w-8 h-8 flex justify-center items-center
                    hover:bg-blue-700 hover:bg-opacity-25 active:bg-blue-600">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                class="w-6 h-6 stroke-current m-2">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M5 12h.01M12 12h.01M19 12h.01M6 12a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0z" />
                            </svg>
                        </div>
                    </button>

                </div>
                <div class="text-base font-bold">{{ trend.content }}</div>
                <!-- chirp count -->
                <div class="text-sm text-gray-600">{{ trend.chirp_count }} Chirps</div>
            </div>
        </div>
        {% endfor %}
        <a href="{{ url_for('main.trends') }}" class="block text-blue-500 hover:bg-gray-800 hover:bg-opacity-25 p-3">Show more</a>
    </div>

    <!-- what's happening -->
    <div class="border-t-8 border-gray-800">
        <div>
            <h2 class="border-b border-gray-700 text-xl font-bold p-3 pl-4">What's happening</h2>
            {% for happening in happenings %}
            <div class="flex flex-row justify-between border-b border-gray-700 p-3
            hover:bg-gray-800 hover:bg-opacity-25">
                <div>
                    <div class="flex flex-row items-center justify-between">
                        <div class="flex flex-row text-sm text-gray-600 space-x-1">
                            <div class="text-white font-bold">{{ happening.label }}</div>
                            <div>⋅</div>
                            <div>{{ happening.time }}</div>
                        </div>
                    </div>
                    <!-- headlines -->
                    <div class="text-lg font-bold">{{ happening.title }}</div>
                </div>
                <!-- img -->
                <div class="w-20 h-20 rounded-2xl overflow-hidden">
                    <img src="{{ url_for('static', filename = 'img/profile_pics/ocean3.jpg') }}" class="w-full h-full object-cover">
                </div>
            </div>
        </div>

        {% endfor %}
        <a href="{{ url_for('main.timeline') }}" class="block text-blue-500 hover:bg-gray-800 hover:bg-opacity-25 p-3">Show more</a>
    </div>
</div>
{% endblock content %}

flask_chirper/templates/lists_addMember.html
/lists/add_member page

flask_chirper/templates/profile_followers.html
{% extends 'layout.html' %}

{% block title %}People following {{ user.name }} (@{{ user.handle }}){% endblock title %}
{% block header %}{{ user.name }}{% endblock header %}


{% block small %}
<div class="text-gray-600 text-s font-normal">@{{ user.handle }}</div>
{% endblock small %}


{% block presvg %}
<a href="{{ url_for('user.profile', handle = user.handle) }}">
    <!-- svg redirects to whatever last page user was on -->
    <div class="svg-bg-div mr-6 cursor-pointer">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
            class="w-6 h-6 stroke-current text-blue-500">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M10 19l-7-7m0 0l7-7m-7 7h18" />
        </svg>
    </div>
</a>
{% endblock presvg %}


{% block tab %}
{% if user != current_user %}
<div class="flex flex-row text-gray-600 font-bold">
    <a href="{{ url_for('user.profile_followersYouKnow', handle = user.handle) }}" class="w-52 h-12 flex justify-center items-center
    hover:bg-blue-800 hover:bg-opacity-25 hover:text-blue-500 whitespace-no-wrap">
        <div class="flex justify-center">Followers you know</div>
    </a>
    <a href="{{ url_for('user.profile_followers', handle = user.handle) }}" class="w-36 h-12 flex justify-center items-center
    hover:bg-blue-800 hover:bg-opacity-25 hover:text-blue-500 text-blue-500 border-b-2 border-blue-500">
        <div class="flex justify-center">Followers</div>
    </a>
    <a href="{{ url_for('user.profile_following', handle = user.handle) }}" class="w-36 h-12 flex justify-center items-center
     hover:bg-blue-800 hover:bg-opacity-25 hover:text-blue-500">
        <div class="">Following</div>
    </a>
    <a href="{{ url_for('user.profile_suggested', handle = user.handle) }}" class="w-36 h-12 flex justify-center items-center
    hover:bg-blue-800 hover:bg-opacity-25 hover:text-blue-500">
        <div class="flex justify-center">Suggested</div>
    </a>
</div>
{% else %}
<div class="flex flex-row text-gray-600 font-bold">
    <a href="{{ url_for('user.profile_followers', handle = user.handle) }}" class="w-1/3 h-12 flex justify-center items-center
    hover:bg-blue-800 hover:bg-opacity-25 hover:text-blue-500 text-blue-500 border-b-2 border-blue-500">
        <div class="flex justify-center">Followers</div>
    </a>
    <a href="{{ url_for('user.profile_following', handle = user.handle) }}" class="w-1/3 h-12 flex justify-center items-center
     hover:bg-blue-800 hover:bg-opacity-25 hover:text-blue-500">
        <div class="">Following</div>
    </a>
    <a href="{{ url_for('user.profile_suggested', handle = user.handle) }}" class="w-1/3 h-12 flex justify-center items-center
    hover:bg-blue-800 hover:bg-opacity-25 hover:text-blue-500">
        <div class="flex justify-center">Suggested</div>
    </a>
</div>
{% endif %}
{% endblock tab %}


{% block content %}
<div class="mt-12">
</div>
{% endblock content %}

flask_chirper/templates/status_likes.html
{% extends 'layout_form.html' %}
{% block title %}Chirps likes{% endblock title %}

{% block content %}
<div class="h-screen sm:bg-gray-900 md:bg-gray-800 md:bg-opacity-100 flex flex-col items-center md:justify-center">
    <div class="flex flex-col bg-gray-900 md:rounded-2xl pb-32 pt-2 h-160">
        <form method="POST" action="" enctype="multipart/form-data">
            <!-- add a special encoding type to our form in order for our to pass our image data properly -->
            <div class="flex flex-col w-148">
                <!-- header -->
                <div class="flex flex-row items-center justify-between border-b border-gray-700 pb-2 px-2">
                    <!-- justify left -->
                    <div class="flex flex-row items-center">
                        <!-- close svg -->
                        <div onclick="history.go(-1)" class="svg-bg-div mr-4 cursor-pointer">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                class="w-6 h-8 stroke-current text-blue-500">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M6 18L18 6M6 6l12 12" />
                            </svg>
                        </div>
                        <div class="text-xl font-bold tracking-wide">Liked by</div>
                    </div>
                </div>

                <!-- scrollable area -->
                <div class="h-144 overflow-y-scroll">

                    <!-- list of folloing users/contacts -->
                    <div>
                        {% for user in post.liked_by %}
                        <a
                            href="{{ url_for('main.messages_counterpart', counterpart_id = user.id, currentuser_id = current_user.id) }}">
                            <div class="flex flex-row border-b border-gray-700
                            hover:bg-gray-800 hover:bg-opacity-25">
                                <!-- user icon -->
                                <div class="w-12 h-12 ml-4 mr-3 my-3">
                                    <div class="w-12 h-12 rounded-full overflow-hidden">
                                        <img src="{{ url_for('static', filename = 'img/profile_pics/' + user.profile_image) }}"
                                            alt="profile pic" class="w-full h-full object-cover">
                                    </div>
                                </div>
                                <!-- link to user page -->
                                <div class="flex flex-col justify-center mt-3 w-full">
                                    <div class="flex flex-row justify-between mr-3">
                                        <div class="flex flex-col justify-center">
                                            <div class="text-tiny font-bold">{{ user.name }}</div>
                                            <div class="text-gray-600 text-tiny -mt-1">@{{ user.handle }}</div>
                                        </div>

                                        {% if user.handle != current_user.handle %}
                                        {% if not current_user.is_following(user) %}
                                        <div>
                                            <form action="{{ url_for('user.follow', handle = user.handle) }}"
                                                method="POST">
                                                <input type="submit" value="Follow"
                                                    class="self-center rounded-full font-bold text-blue-500 px-4 h-8 bg-transparent cursor-pointer
                                                border border-blue-500 focus:outline-none hover:bg-blue-800 hover:bg-opacity-25 active:bg-blue-700">
                                            </form>
                                        </div>
                                        {% else %}
                                        <div>
                                            <form action="{{ url_for('user.unfollow', handle = user.handle) }}"
                                                method="POST">
                                                <input type="submit" value="Following" class="self-center rounded-full font-bold text-white px-4 h-8 bg-transparent cursor-pointer
                                                bg-blue-500 focus:outline-none hover:bg-red-700 focus:bg-opacity-75">
                                            </form>
                                        </div>
                                        {% endif %}
                                        {% endif %}

                                    </div>
                                    <div class="text-tiny my-2">{{ user.bio }}</div>
                                </div>
                            </div>
                        </a>
                        {% endfor %}
                    </div>
                    <!-- end list -->
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

flask_chirper/templates/subdomain_ads.html
ads